CREATE DATABASE ContactForm;
USE ContactForm;
DROP TABLE IF EXISTS CONTACT;
CREATE TABLE CONTACT(
		pk_contact 					INT UNSIGNED NOT NULL auto_increment,
		name						VARCHAR(120) NOT NULL,
		email 						VARCHAR(120) NOT NULL,
		website		                VARCHAR(120) NOT NULL DEFAULT "",
		message						VARCHAR(300) NOT NULL,
		added_date 					TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
		primary key(pk_contact)
)type=innodb DEFAULT CHARACTER SET utf8	COLLATE utf8_general_ci;

INSERT INTO wp_libroreclamacion(FECHA, ORIGEN, APELLIDOS, NOMBRES, TIPODOCUMENTO,NUMERODOCUMENTO, DIRECCION, DISTRITO, PROVINCIA, TELEFONO,EMAIL,`TUTOR-NOMBRES`, `TUTOR-APELLIDOS`, `TUTOR-TIPODOCUMENTO`,`TUTOR-NUMERODOCUMENTO`,TIPO, SERVICIO, DESCRIPCION, FORMARESPUESTA)\r\n\t\tVALUES(\tnow(),'100','APELLIDOS','NOMBRES','1','40290904','DIRECCION','DISTRITO','PROVINCIA','TELEFONO','EMAIL','TUTOR-NOMBRES', 'TUTOR-APELLIDOSSS', '1','40290904','1','1','DESCRIPCION','1')
CONSOLA DE DEPURACIÓN


INSERT INTO `wp_libroreclamacion`
(`FECHA`, `ORIGEN`, `APELLIDOS`, `NOMBRES`, `TIPODOCUMENTO`, 
`NUMERODOCUMENTO`, `DIRECCION`, `DISTRITO`, `PROVINCIA`, `TELEFONO`, 
`EMAIL`,`TUTOR-NOMBRES`, `TUTOR-APELLIDOS`, `TUTOR-TIPODOCUMENTO`, 
`TUTOR-NUMERODOCUMENTO`,`TIPO`, `SERVICIO`, `DESCRIPCION`, `FORMARESPUESTA`) 
VALUES 
(
	now(),100,'APELLIDOS','NOMBRES','1',
'40290904','DIRECCION','DISTRITO','PROVINCIA','TELEFONO',
"EMAIL","TUTOR-NOMBRES", "TUTOR-APELLIDOS", "1",
'40290904','1','1','DESCRIPCION','1'
)

"INSERT INTO wp_libroreclamacion\r\n\t\t(FECHA, ORIGEN, APELLIDOS, NOMBRES, TIPODOCUMENTO,\r\n\t\tNUMERODOCUMENTO, DIRECCION, DISTRITO, PROVINCIA, TELEFONO,\r\n\t\tEMAIL,`TUTOR-NOMBRES`, `TUTOR-APELLIDOS`, `TUTOR-TIPODOCUMENTO`,`TUTOR-NUMERODOCUMENTO`,\r\n\t\tTIPO, SERVICIO, DESCRIPCION, FORMARESPUESTA)\r\n\t\tVALUES\r\n\t\t(\tnow(),'100','cdsc','cds','1',\r\n\t\t'sdcsdc','ccdc','dcsdcs','csdcsdc','cdscdsc',\r\n\t\t'mcmollehuara@gmail.com','sdc', 'cdscs', '1','sdcsdcd',\r\n\t\t'1','1','csdcdscdsc','')"



"INSERT INTO wp_libroreclamacion\r\n\t\t(FECHA, ORIGEN, APELLIDOS, NOMBRES, TIPODOCUMENTO,\r\n\t\tNUMERODOCUMENTO, DIRECCION, DISTRITO, PROVINCIA, TELEFONO,\r\n\t\tEMAIL,`TUTOR-NOMBRES`, `TUTOR-APELLIDOS`, `TUTOR-TIPODOCUMENTO`,`TUTOR-NUMERODOCUMENTO`,\r\n\t\tTIPO, SERVICIO, DESCRIPCION, FORMARESPUESTA)\r\n\t\tVALUES\r\n\t\t(\tnow(),'100','bfg','fdbgf','1',\r\n\t\t'gbfg','bgbfg','bfgbfg','bfg','bgfbfgb',\r\n\t\t'mcmollehuara@gmail.com','bfg', 'bgfb', '1','bfgb',\r\n\t\t'1','1','bfgbgf','1')"
